### ISSUE TITLE
trans 不用加文件名吗?

### ISSUE THREAD

**Issue by stevenyangecho** [overtrue/laravel-lang#1]
readme 里面

    echo trans('user_not_exists'); // 用户不存在
    echo trans('email_has_registed', ['email' => 'anzhengchao@gmail.com']);

怎么我用都必须要 trans('demo.user_not_exists') ?

你是怎么做到可以不用加 demo的?

**Comment by overtrue** [comment]
@stevenyangecho  sorry,是我的错，我改一下，是需要加文件名的
