### ISSUE TITLE
为什么我的会报错啊

### ISSUE THREAD

**Issue by zhangwei900808** [overtrue/laravel-lang#11]
我已经在homesteaad里面执行了composer命令，但是phpstorm项目里面还是出错了啊：
![image](https://cloud.githubusercontent.com/assets/4385154/17830288/15efda72-66fa-11e6-97d9-28d3143b2a8a.png)
![image](https://cloud.githubusercontent.com/assets/4385154/17830289/1d756ba4-66fa-11e6-9058-434e0353cf0d.png)

**Comment by overtrue** [comment]
@zhangwei900808 提问能否带上详细，出错是什么错？

**Comment by zhangwei900808** [comment]
![image](https://cloud.githubusercontent.com/assets/4385154/17835010/b056af28-678b-11e6-89c2-a79d50979816.png)

**Comment by overtrue** [comment]
@zhangwei900808 请检查你的安装结果，也许就没安装成功。。。

**Comment by zhangwei900808** [comment]
可以了，我第二次执行为什么就可以了？第一次也是成功的我肯定不会记错的，真是日了狗了
![image](https://cloud.githubusercontent.com/assets/4385154/17835498/f5e11cf2-67a1-11e6-82ba-bfaf2a2c389e.png)

**Comment by zhangwei900808** [comment]
我知道了这个命令一定要到项目文件夹下来执行
