### ISSUE TITLE
cmd 下报错

### ISSUE THREAD

**Issue by yangliulnn** [overtrue/laravel-lang#12]
windows 下报错：

> 'cp' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。

对应代码：
`$process = new Process("cp -r{$force} $files $targetPath");`

**Comment by overtrue** [comment]
sorry, 请不要在 windows 下用这个命令，这是 linux 命令。

**Comment by yangliulnn** [comment]
我知道，我在想能否使用 php 实现兼容 Windows 。

**Comment by overtrue** [comment]
@yangliulnn 能啊，但是没有必要啊，反正你的项目最终都是要在 linux 服务器上去运行嘛
