### ISSUE TITLE
Use de for de-CH, de-AT and so on

### ISSUE THREAD

**Issue by amenk** [overtrue/laravel-lang#13]
I want to use the German locale pack also for locales of austria and switzerland. How to do so? Do I have to copy the files?

**Comment by overtrue** [comment]
@amenk All of locale pack come from https://github.com/caouecs/Laravel-lang, there is only one folder called `de`, So please forgive me for not quite understand your needs, can provide a more detailed description of the scene it?

**Comment by amenk** [comment]
jep, there is only one folder `de` - but it is perfectly fine to use that for `de-AT` as well (I set the locale to `de-AT`for other - non-language - reasons).
See https://github.com/overtrue/laravel-lang/pull/14

**Comment by overtrue** [comment]
@amenk ok, what do you mean is you created a folder named `de-AT` and put some translation files in it but not all of `de` files ?

**Comment by amenk** [comment]
No i did not create any folder. But when I set the locale to `de-AT` english is still used. With my patch, it falls back to `de`

**Comment by overtrue** [comment]
OK, I got it.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-lang/releases/tag/3.0.3
