### ISSUE TITLE
laravel5.4之前安装有用，现在没用了

### ISSUE THREAD

**Issue by maokeyang** [overtrue/laravel-lang#17]
laravel5.4之前安装有用，今天尝试了两次 都没有效果

**Comment by overtrue** [comment]
我现在用的 5.4 呢，正常用啊，你的安装步骤说一下

**Comment by Sunappnio** [comment]
我的很奇怪，在本机测试环境能行，传到线上变英文了

**Comment by Sunappnio** [comment]
本地环境 macos 10.12 php7.0 valet
线上环境 ubuntu 14.04 php7.0 nginx
config cache各种都清除了

**Comment by Sunappnio** [comment]
解决了，因为zh-CN和zh-cn文件夹的区别，mac不区分大小写

**Comment by overtrue** [comment]
哈哈

**Comment by maokeyang** [comment]
不好意思 超哥 最近忙 忘回了。我手动改的文件。。@Sunappnio  多谢 我试试
