### ISSUE TITLE
3.0.9 introduced a break in backward compatibility

### ISSUE THREAD

**Issue by forxer** [overtrue/laravel-lang#38]
Since the addJsonPath method was introduced in version 5.5 of Laravel, the use of it in your package breaks compatibility with Laravel <5.5

https://laravel.com/api/5.4/search.html?search=addJsonPath
https://laravel.com/api/5.5/search.html?search=addJsonPath

You should use Semver to avoid this. Besides, it would be nice to indicate the compatability requirements in your composer.json file.

**Comment by overtrue** [comment]
@forxer Plz take a try: https://github.com/overtrue/laravel-lang/commit/11d8386a5dee3cfedf4ee7e2da6af0d3b3fe268a

**Comment by overtrue** [comment]
You are welcome.

Vincent Garnier <notifications@github.com>于2018年9月3日 周一下午6:17写道：
