### ISSUE TITLE
Call to undefined function Overtrue\LaravelLang\resource_path() 

### ISSUE THREAD

**Issue by grudge61** [overtrue/laravel-lang#4]
After last update when I do a php artisan clear-compiled I recive the following error:

[Symfony\Component\Debug\Exception\FatalErrorException]          
Call to undefined function Overtrue\LaravelLang\resource_path()                                                                   

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

**Comment by overtrue** [comment]
@grudge61 OK, I will fix it.

**Comment by overtrue** [comment]
@grudge61 lumen app?

**Comment by overtrue** [comment]
@grudge61 PLZ take a try the new version: `composer require "overtrue/laravel-lang:v2.1.x-dev`, and document is here: https://github.com/overtrue/laravel-lang/tree/v2.1

**Comment by grudge61** [comment]
Nope, laravel app. It works with v2.1.x-dev version! thanks a lot!

**Comment by overtrue** [comment]
laravel app? what is the version of you Laravel?

**Comment by overtrue** [comment]
@grudge61 Hi, I released the 3.0.0. 😄 https://github.com/overtrue/laravel-lang/releases/tag/3.0.0
