### ISSUE TITLE
MAC使用php artisan lang:publish zh-CN 报错

### ISSUE THREAD

**Issue by richarduncle** [overtrue/laravel-lang#41]
chenjinhaodeMacBook-Pro:rarone_watch chenjinhao$ php artisan lang:publish zh-CN         

cp: /Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/src/zh-CN /Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/json/zh-CN.json: No such file or directory

published languages (no overwrite): ["zh-CN"].

**Comment by overtrue** [comment]
确认一下 `/Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/src/zh-CN` 与 `/Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/json/zh-CN.json` 是否存在

**Comment by richarduncle** [comment]
![image](https://user-images.githubusercontent.com/19268769/51451640-3f2e0000-1d71-11e9-8a92-2fe65287dc6f.png)
![image](https://user-images.githubusercontent.com/19268769/51451649-47863b00-1d71-11e9-99a9-0b85a7df0d2e.png)

**Comment by richarduncle** [comment]
![image](https://user-images.githubusercontent.com/19268769/51452234-22df9280-1d74-11e9-9d56-d1de01a0fdfc.png)
`php artisan lang:publish zh-CN`
结果
"'cp' '-rn' '/Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/src/zh-CN /Applications/MAMP/htdocs/rarone_watch/vendor/caouecs/laravel-lang/json/zh-CN.json' '/Applications/MAMP/htdocs/rarone_watch/resources/lang/'"

**Comment by overtrue** [comment]
OK 我明白了

**Comment by overtrue** [comment]
107 - 109 改为：
```php
$files = implode(' ', \array_map('escapeshellarg', $files));
$targetPath = escapeshellarg($targetPath);
$process = Process::fromShellCommandline("cp -r{$force} {$files} {$targetPath}");
```

**Comment by richarduncle** [comment]
chenjinhaodeMacBook-Pro:rarone_watch chenjinhao$ php artisan lang:publish zh-CN

In Publish.php line 109:
                                                                                      
  Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()

**Comment by overtrue** [comment]
composer update symfony/process

**Comment by ChenRuihua** [comment]
3.0.14版，107-109改成如上后，报错如图。

<img width="1466" alt="xnip2019-01-22_12-50-32" src="https://user-images.githubusercontent.com/46486133/51513170-5d186500-1e44-11e9-93e7-efe4cece62b7.png">

**Comment by overtrue** [comment]
@ChenRuihua No space left... 磁盘满了兄弟

**Comment by ChenRuihua** [comment]
并没有。
<img width="773" alt="xnip2019-01-22_12-55-07" src="https://user-images.githubusercontent.com/46486133/51513273-052e2e00-1e45-11e9-9cce-e4aa3f4b51a0.png">

**Comment by ChenRuihua** [comment]
@overtrue 老眼昏花看串行了。确实满了。老大。见笑了。
