### ISSUE TITLE
Old version of translation

### ISSUE THREAD

**Issue by mohamedsabil83** [overtrue/laravel-lang#55]
When I try to publish the translation file, I note that was an old version of [Caouse-laravel-lang](https://github.com/caouecs/Laravel-lang) files.

I hope to check it to publish the newest translation files.

**Comment by overtrue** [comment]
plz check the version of `overtrue/laravel-lang` and `caouecs/laravel-lang` by the following command:

```bash
$ composer info overtrue/laravel-lang
$ composer info caouecs/laravel-lang
```

And which version of Laravel you used?

**Comment by mohamedsabil83** [comment]
**Laravel** 7.18.0
**Overtrue** 3.0.18
**caouecs** 4.0.11

**Comment by overtrue** [comment]
Plz upgrade to 4.0 https://github.com/overtrue/laravel-lang/releases/tag/4.0.0

**Comment by mohamedsabil83** [comment]
Thank you for updating and sorry for the delay replying

**Comment by overtrue** [comment]
@mohamedsabil83 😃
