### ISSUE TITLE
caouecs/laravel-lang更新到Laravel-lang/lang

### ISSUE THREAD

**Issue by fishtailstudio** [overtrue/laravel-lang#61]
caouecs/laravel-lang更新到Laravel-lang/lang已经有段时间了，也看到了本项目依赖已经更改，但是好像还没打标签，导致packagist上还没更改，最近composer update老是提示 “Package caouecs/laravel-lang is abandoned, you should avoid using it.” 。

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-lang/releases/tag/4.1.0

**Comment by fishtailstudio** [comment]
okk
