### ISSUE TITLE
版本化建议

### ISSUE THREAD

**Issue by suyar** [overtrue/laravel-lang#64]
推荐和 `laravel-lang/lang` 一致，用大版本的版本号来对应不同的 `laravel` 版本，例如：

| Laravel version                     | Composer command                                  |
|-------------------------------------|---------------------------------------------------|
| Laravel 8.x                         | `composer require overtrue/laravel-lang:~7.0` |
| Laravel 7.x and new directory names | `composer overtrue/laravel-lang:~7.0` |
| Laravel 7.x                         | `composer require overtrue/laravel-lang:~6.1` |
| Laravel 6.x                         | `composer require overtrue/laravel-lang:~5.0` |
| Laravel 5.8                         | `composer require overtrue/laravel-lang:~4.0` |
| Laravel 5.1-5.7                     | `composer require overtrue/laravel-lang:~3.0` |
| Laravel 5                           | `composer require overtrue/laravel-lang:~2.0` |
| Laravel 4                           | `composer require overtrue/laravel-lang:~1.0` |

否则用户不知道哪个版本的翻译对应到哪个 `laravel` 版本。

**Comment by overtrue** [comment]
好的

**Comment by aogg** [comment]
哪里有overtrue/laravel-lang:~5.0版本

**Comment by overtrue** [comment]
已重新整理并发布新版：

| Laravel version                     | Composer command                                  |
|-------------------------------------|---------------------------------------------------|
| Laravel 7.x-8.x                   | `composer require overtrue/laravel-lang:~5.0` |
| Laravel 6.x                         | `composer require overtrue/laravel-lang:~4.0` |
| Laravel 5.8                         | `composer require overtrue/laravel-lang:~3.0` |
| Laravel 5.1-5.7                     | `composer require overtrue/laravel-lang:~2.0` |
| Laravel 5                           | `composer require overtrue/laravel-lang:~1.0` |
