### ISSUE TITLE
"overtrue/laravel-lang": "~3.0", lang 'zh_CN' not found.

### ISSUE THREAD

**Issue by liutao-me** [overtrue/laravel-lang#69]
环境：
```
"laravel/framework": "5.5.*",
"overtrue/laravel-lang": "~3.0",
```

按照 readme 所述，`php artisan lang:publish zh_CN ` ，会出现：
`lang 'zh_CN' not found.`

**换成 zh-CN 就可以正常执行。**
对于 3.0 版本，是否应该在 readme 中说明一下？

**Comment by overtrue** [comment]
已修复
