### ISSUE TITLE
Can't load translation files

### ISSUE THREAD

**Issue by uxweb** [overtrue/laravel-lang#7]
Hi, i'm using Laravel Framework version 5.2.31,

i have installed the package according to the main page instructions but i still see validation errors in english instead in the locale i have set in config/app.php.

I discovered that within the registerLoader method in TranslationServiceProvider there is a reference to this method:

```
app()->basePath('vendor/caouecs/laravel-lang/src/'),
```

And looking into the basePath Application class it does not accept any parameters. This line will output just the base path and not the base path with 'vendor/caouecs/laravel-lang/src/' concatenated, this is preventing the FIleLoader class to find the translation files.

there is a function in Illuminate/Foundation/helpers.php that it does accept a path parameter and it will concatenate it to the base path:

```
if (! function_exists('base_path')) {
    /**
     * Get the path to the base of the install.
     *
     * @param  string  $path
     * @return string
     */
    function base_path($path = '')
    {
        return app()->basePath().($path ? DIRECTORY_SEPARATOR.$path : $path);
    }
}
```

I think this will work good.

Could you please fix this?

Thanks for this great package, i love it!

**Comment by overtrue** [comment]
@uxweb Thank you very much. It's my mistake, I pushed without check it. 👍

**Comment by uxweb** [comment]
@overtrue Thank you!!

**Comment by overtrue** [comment]
You are welcome. 😃
