### ISSUE TITLE
WINDOWS  laravel  php artisan lang:publish zh-CN,zh-HK,zh-TW  报错

### ISSUE THREAD

**Issue by licecn** [overtrue/laravel-lang#76]
'cp' is not recognized as an internal or external command,
operable program or batch file.

如何解决

**Comment by overtrue** [comment]
windows 的话，自己拷贝 vendor/laravel-langs/ 下对应的语言目录吧

**Comment by licecn** [comment]
> windows 的话，自己拷贝 vendor/laravel-langs/ 下对应的语言目录吧

我靠 你这回复的也太快了啊 ，，，我 刚刚用 git bush 运行了命令  成功了。谢啦。

我想问问  你是怎么这么快 回复的啊 ，难道你一直看着吗？

**Comment by overtrue** [comment]
有邮件通知啊

**Comment by licecn** [comment]
哦哦 。 原来如此，谢啦。

**Comment by overtrue** [comment]
不客气哈
