### ISSUE TITLE
laravel-lang6.0版本问题

### ISSUE THREAD

**Issue by yesccx** [overtrue/laravel-lang#85]
这次适配`laravel9.x`发布的`laravel-lang6.0`，貌似不是在上一个版本`5.0.2`基础下迭代发布的，导致之前修复的几个BUG又出现了。

**Comment by overtrue** [comment]
比如？

**Comment by yesccx** [comment]
[cb82a2f](https://github.com/overtrue/laravel-lang/commit/cb82a2f1e5fd1c7313a5aa1531f02cd5838969e4) 比如这里修复的BUG，6.0的代码里没有包含这部分修复的代码。

**Comment by yesccx** [comment]
> 比如？

[cb82a2f](https://github.com/overtrue/laravel-lang/commit/cb82a2f1e5fd1c7313a5aa1531f02cd5838969e4) 比如这里修复的BUG，6.0的代码里没有包含这部分修复的代码。

**Comment by overtrue** [comment]
感谢提醒，因为 master after 5.x 的原因，已经合并过来了。
